---
cog_bundle_version: 4
name: k8s
description: Interact with a Kubernetes cluster
version: 0.0.18
author: Marc Campbell <marc.e.campbell@gmail.com>, Joe Toscano <jtoscano42@gmail.com>
docker: 
  image: retracedhq/k8s-cog
  tag: 0.0.18
permissions:
  - k8s:read
  - k8s:write
commands:
  pods:
    description: List all pods in the named cluster
    executable: /home/bundle/k8s-cog/lib/cmd/pods.js
    arguments: '<cluster>'
    rules:
      - when command is k8s:pods must have k8s:read
  deploy:
    description: Immediately deploy all k8s config declarations in a public Github repo
    executable: /home/bundle/k8s-cog/lib/cmd/deploy.js
    arguments: '<cluster> <sha>'
    rules:
      - when command is k8s:deploy must have k8s:write
  logs:
    description: Show recent logs from a given pod
    executable: /home/bundle/k8s-cog/lib/cmd/logs.js
    arguments: '<cluster> <pod>'
    options: 
      count:
        description: maximum number of lines to fetch
        type: int
        required: false
        short_flag: c    
    rules:
      - when command is k8s:logs must have k8s:read      
templates:
  pods:
    body: |
      | NAME | READY | STATUS | RESTARTS | AGE |
      |------|-------|--------|----------|-----|
      ~each var=$results~
      |~$item.name~|~$item.ready~|~$item.status~|~$item.restarts~|~$item.age~|
      ~end~
  deploy:
    body: |
      | NAME | RESULT |
      |------|--------|
      ~each var=$results~
      |~$item.name~|~$item.result~|
      ~end~
  logs:
    body: |
      ```      
      ~each var=$results~
      ~$item.line~
      ~end~
      ```
    