---
cog_bundle_version: 4
name: k8s
description: Interact with a Kubernetes cluster
version: 0.0.6
author: Marc Campbell <marc.e.campbell@gmail.com>
docker: 
  image: retracedhq/k8s-cog
  tag: 0.0.6
permissions:
  - k8s:read
  - k8s:write
commands:
  pods:
    description: List all pods in the named cluster
    executable: node /home/bundle/lib/cmd/pods.js
    arguments: '<cluster>'
    rules:
      - when command is k8s:pods must have k8s:read
  deploy:
    description: Immediately deploy all k8s config declarations in a public Github repo
    executable: node /home/bundle/lib/cmd/deploy.js
    arguments: '<cluster> <sha>'
    rules:
      - when command is k8s:deploy must have k8s:write      
templates:
  pods:
    body: |
      | NAME | READY | STATUS | RESTARTS | AGE |
      |------|-------|--------|----------|-----|
      ~each var=\$results~
      |~\$item.name~|~\$item.ready~|~\$item.status~|~\$item.restarts~|~\$item.age~|
      ~end~
  deploy:
    body: |
      ~each var=\$results~
      ~\$item~
      ~end~
    