K8S_CLUSTER_COUNT: '2'
K8S_DEFAULT_CLUSTER: 'staging'

K8S_CLUSTER_0_NAME: 'staging'
K8S_CLUSTER_0_ENDPOINT: 'https://1.2.3.4'
K8S_CLUSTER_0_CA_CERT: 'U0RLR0pXT0VHSkRTQUpHQURTTGcK'
K8S_CLUSTER_0_AUTH_TYPE: 'username'
K8S_CLUSTER_0_USERNAME: 'admin'
K8S_CLUSTER_0_PASSWORD: 'lhd6aFGdIIqmTnWC'

K8S_CLUSTER_1_NAME: 'production'
K8S_CLUSTER_1_ENDPOINT: 'https://5.6.7.8'
K8S_CLUSTER_1_CA_CERT: 'QUpER1Nha2RqZ2tkbmdvaXk0OTE4eTI5dG9paHdsa2dqCg=='
K8S_CLUSTER_1_AUTH_TYPE: 'username'
K8S_CLUSTER_1_USERNAME: 'admin'
K8S_CLUSTER_1_PASSWORD: '2iuhtksjnJGd235n'
